# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec47030095f2c77019f9a018b1bf5c054e699fd9935163357016dd1d9868bf64ae78364430bc6ad35ebdcf9c3a6e6f3b0ca715076da05060bf324fc0ec3263f

test:
  secret_key_base: 8870f05459d8d7c74208bb16d52a3ef390b201697eecd0b6b38354d32ebcf42dd0ee9f1ed8511649c289f728ea9eac21dbf0127204e84820e58c9e0f7cca1e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
